=== satishkumar9142/Task/XML/target/classes/EventFramework.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
           xmlns:dis="http://attunedlabs.com/internalevents/Dispatcher" 
           attributeFormDefault="unqualified" elementFormDefault="unqualified" 
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import schemaLocation="schema1.xsd" namespace="http://attunedlabs.com/internalevents/Dispatcher" />
  <xs:element name="EventFramework">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="DispatchChanels">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="DispatchChanel">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="ChanelImplementation">
                      <xs:complexType>
                        <xs:attribute name="beanRefid" type="xs:string" use="required" />
                        <xs:attribute name="fqcn" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="ChanelConfiguration" type="xs:string" />
                  </xs:sequence>
                  <xs:attribute name="description" type="xs:string" use="required" />
                  <xs:attribute name="id" type="xs:string" use="required" />
                  <xs:attribute name="isEnabled" type="xs:boolean" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="SystemEvents">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="SystemEvent">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="CamelSystemEventBuilder">
                      <xs:complexType>
                        <xs:attribute name="beanRefid" type="xs:string" use="required" />
                        <xs:attribute name="fqcn" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="EventDispatchers">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="EventDispatcher">
                            <xs:complexType>
                              <xs:sequence>
                              <xs:element ref="dis:DispatchChanelId" />
                                <xs:element name="EventTransformation">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="CustomTransformer">
                                        <xs:complexType>
                                          <xs:attribute name="fqcn" type="xs:string" use="required" />
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="Type" type="xs:string" use="required" />
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="description" type="xs:string" use="required" />
                  <xs:attribute name="id" type="xs:string" use="required" />
                  <xs:attribute name="isEnabled" type="xs:boolean" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Events">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="Event">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="EventParams">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="EventParam">
                            <xs:complexType>
                              <xs:attribute name="dataType" type="xs:string" use="required" />
                              <xs:attribute name="name" type="xs:string" use="required" />
                              <xs:attribute name="validationRegEx" type="xs:string" use="required" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="CamelEventProducer">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="CamelProducerConfig">
                            <xs:complexType>
                              <xs:attribute name="component" type="xs:string" use="required" />
                              <xs:attribute name="feature" type="xs:string" use="required" />
                              <xs:attribute name="raiseOn" type="xs:string" use="required" />
                              <xs:attribute name="serviceName" type="xs:string" use="required" />
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="CamelEventBuilder">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element minOccurs="0" name="EventBuilder">
                                  <xs:complexType>
                                    <xs:attribute name="beanRefid" type="xs:string" use="required" />
                                    <xs:attribute name="fqcn" type="xs:string" use="required" />
                                  </xs:complexType>
                                </xs:element>
                                <xs:element minOccurs="0" name="OGNLMapping">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="Source">
                                        <xs:complexType>
                                          <xs:sequence>
                                            <xs:element maxOccurs="unbounded" name="EventMapping">
                                              <xs:complexType>
                                                <xs:attribute name="destination" type="xs:string" use="required" />
                                                <xs:attribute name="source" type="xs:string" use="required" />
                                              </xs:complexType>
                                            </xs:element>
                                          </xs:sequence>
                                          <xs:attribute name="from" type="xs:string" use="required" />
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute name="type" type="xs:string" use="required" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="EventDispatchers">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="EventDispatcher">
                            <xs:complexType>
                              <xs:sequence>
								<xs:element ref="dis:DispatchChanelId" />   
                                <xs:element name="EventTransformation">
                                  <xs:complexType>
                                    <xs:sequence minOccurs="0">
                                      <xs:element minOccurs="0" name="CustomTransformer">
                                        <xs:complexType>
                                          <xs:attribute name="fqcn" type="xs:string" use="required" />
                                        </xs:complexType>
                                      </xs:element>
									  <xs:element minOccurs="0" ref="dis:XSLTName" /> 
                                    </xs:sequence>
                                    <xs:attribute name="Type" type="xs:string" use="required" />
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="description" type="xs:string" use="required" />
                  <xs:attribute name="id" type="xs:string" use="required" />
                  <xs:attribute name="isEnabled" type="xs:boolean" use="required" />
                  <xs:attribute name="type" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== satishkumar9142/Task/XML/target/classes/eventframework.xml
<?xml version="1.0" encoding="UTF-8"?>
<EventFramework xmlns:dis="http://attunedlabs.com/internalevents/Dispatcher" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="eventframework.xsd" >
	<DispatchChanels>
		<DispatchChanel description="file store" id="FILE_STORE" isEnabled="true">
			<ChanelImplementation beanRefid="fileStoreDispatcher" fqcn="com.attunedlabs.eventframework.dispatcher.chanel.FileStoreDispatchChanel"/>
			<ChanelConfiguration>
				{"filepath":"/home/ubuntu/LogDispatcher","filename":"LogDispatchChanel.txt"}
			</ChanelConfiguration>
		</DispatchChanel>
		<DispatchChanel description="event file store" id="EVT_FILE_STORE" isEnabled="false">
			<ChanelImplementation beanRefid="fileEventStoreDispatcher" fqcn="com.attunedlabs.eventframework.dispatcher.chanel.FileStoreDispatchChanel"/>
			<ChanelConfiguration>
				{"filepath":"/home/ubuntu/LogDispatcher","filename":"EventDispatchChanel.txt"}
			</ChanelConfiguration>
		</DispatchChanel>
		<DispatchChanel description="rest client" id="REST_CLIENT" isEnabled="false">
			<ChanelImplementation beanRefid="restClientDispatcher" fqcn="com.attunedlabs.eventframework.dispatcher.chanel.RestClientPostDispatchChanel"/>
			<ChanelConfiguration> {"restpath":"http://localhost:9080/baseroute"}
			</ChanelConfiguration>
		</DispatchChanel>
		<DispatchChanel description="print rest client" id="PRINT_REST_CLIENT" isEnabled="false">
			<ChanelImplementation beanRefid="restClientDispatcher" fqcn="com.attunedlabs.eventframework.dispatcher.chanel.RestClientPostDispatchChanel"/>
			<ChanelConfiguration>
				{"restpath":"http://192.168.1.120:9090/printservice"}
			</ChanelConfiguration>
		</DispatchChanel>
	</DispatchChanels>
	<SystemEvents>
		<SystemEvent description="Standard Event for failure of every service Type" id="SERVICE_COMPLETION_FAILURE" isEnabled="true">
			<CamelSystemEventBuilder beanRefid="ServiceEventBuilder" fqcn="com.attunedlabs.eventframework.camel.eventproducer.ServiceCompletionFailureEventBuilder"/>
			<EventDispatchers>
				<EventDispatcher>
					<dis:DispatchChanelId>FILE_STORE</dis:DispatchChanelId>
					<EventTransformation Type="CUSTOM">
						<CustomTransformer fqcn="com.attunedlabs.eventframework.dispatcher.transformer.CustomLeapEventTransformer"/>
					</EventTransformation>
				</EventDispatcher>
			</EventDispatchers>
		</SystemEvent>
		<SystemEvent description="Standard Event for sucess of every service Type" id="SERVICE_COMPLETION_SUCCESS" isEnabled="false">
			<CamelSystemEventBuilder beanRefid="ServiceEventBuilder" fqcn="com.attunedlabs.eventframework.camel.eventproducer.ServiceCompletionSuccessEventBuilder"/>
			<EventDispatchers>
				<EventDispatcher>
					<dis:DispatchChanelId>FILE_STORE</dis:DispatchChanelId>
					<EventTransformation Type="CUSTOM">
						<CustomTransformer fqcn="com.attunedlabs.eventframework.dispatcher.transformer.CustomLeapEventTransformer"/>
					</EventTransformation>
				</EventDispatcher>
			</EventDispatchers>
		</SystemEvent>
	</SystemEvents>
	<Events>
		<Event description="polineitem unloaded" id="POLINEITEM_UNLOADED" isEnabled="true" type="internal">
			<EventParams>
				<EventParam dataType="string" name="productid" validationRegEx=""/>
				<EventParam dataType="string" name="tenantid" validationRegEx=""/>
				<EventParam dataType="string" name="servicetype" validationRegEx=""/>
			</EventParams>
			<CamelEventProducer>
				<CamelProducerConfig component="com.attunedlabs.datasource.service.InsertService" feature="polineitem" raiseOn="success" serviceName="baseContext"/>
				<CamelEventBuilder type="OGNL">
					<OGNLMapping>
						<Source from="CamelExchange">
							<EventMapping destination="eventParam['servicetype']" source="In.headers['servicetype']"/>
							<EventMapping destination="eventParam['tenant']" source="In.headers['tenantid']"/>
						</Source>
					</OGNLMapping>
				</CamelEventBuilder>
			</CamelEventProducer>
			<EventDispatchers>
				<EventDispatcher>
					<dis:DispatchChanelId>FILE_STORE</dis:DispatchChanelId>
					<EventTransformation Type="XML-XSLT">
						<dis:XSLTName>eventxmlTransformation.xsl</dis:XSLTName>
					</EventTransformation>
				</EventDispatcher>
			</EventDispatchers>
		</Event>
		<Event description="inventory updated" id="INVENTORY_UPDATED" isEnabled="false" type="internal">
			<EventParams>
				<EventParam dataType="string" name="policyid" validationRegEx=""/>
				<EventParam dataType="string" name="data" validationRegEx=""/>
				<EventParam dataType="string" name="servicetype" validationRegEx=""/>
			</EventParams>
			<CamelEventProducer>
				<CamelProducerConfig component="com.attunedlabs.datasource.dao.UpdateInventory" feature="polineitem" raiseOn="success" serviceName="baseContext"/>
				<CamelEventBuilder type="CUSTOM">
					<EventBuilder beanRefid="inventoryUpdateBuilder" fqcn="com.attunedlabs.eventframework.camel.eventbuilder.InventoryUpdateEventBuilder"/>
				</CamelEventBuilder>
			</CamelEventProducer>
			<EventDispatchers>
				<EventDispatcher>
					<dis:DispatchChanelId>EVT_FILE_STORE</dis:DispatchChanelId>
					<EventTransformation Type="CUSTOM">
						<CustomTransformer fqcn="com.attunedlabs.eventframework.dispatcher.transformer.CustomLeapEventTransformer"/>
					</EventTransformation>
				</EventDispatcher>
			</EventDispatchers>
		</Event>
		<Event description="polineitem processed" id="POLINEITEM_PROCESSED" isEnabled="false" type="internal">
			<EventParams>
				<EventParam dataType="string" name="eventid" validationRegEx=""/>
				<EventParam dataType="string" name="tenantid" validationRegEx=""/>
				<EventParam dataType="string" name="servicetype" validationRegEx=""/>
			</EventParams>
			<CamelEventProducer>
				<CamelProducerConfig component="" feature="polineitem" raiseOn="success" serviceName="baseContext"/>
				<CamelEventBuilder type="OGNL">
					<OGNLMapping>
						<Source from="CamelExchange">
							<EventMapping destination="eventParam['servicetype']" source="In.headers['servicetype']"/>
							<EventMapping destination="eventParam['tenant']" source="In.headers['tenantid']"/>
						</Source>
					</OGNLMapping>
				</CamelEventBuilder>
			</CamelEventProducer>
			<EventDispatchers>
				<EventDispatcher>
					<dis:DispatchChanelId>EVT_FILE_STORE</dis:DispatchChanelId>
					<EventTransformation Type="JSON"/>
				</EventDispatcher>
			</EventDispatchers>
		</Event>
		<Event description="polineitem process failed" id="POLINEITEM_PROC_FAILED" isEnabled="false" type="internal">
			<EventParams>
				<EventParam dataType="string" name="eventid" validationRegEx=""/>
				<EventParam dataType="string" name="tenantid" validationRegEx=""/>
				<EventParam dataType="string" name="servicetype" validationRegEx=""/>
			</EventParams>
			<CamelEventProducer>
				<CamelProducerConfig component="" feature="polineitem" raiseOn="failure" serviceName="baseContext"/>
				<CamelEventBuilder type="OGNL">
					<OGNLMapping>
						<Source from="CamelExchange">
							<EventMapping destination="eventParam['servicetype']" source="In.headers['servicetype']"/>
							<EventMapping destination="eventParam['tenant']" source="In.headers['tenantid']"/>
						</Source>
					</OGNLMapping>
				</CamelEventBuilder>
			</CamelEventProducer>
			<EventDispatchers>
				<EventDispatcher>
					<dis:DispatchChanelId>EVT_FILE_STORE</dis:DispatchChanelId>
					<EventTransformation Type="CUSTOM">
						<CustomTransformer fqcn="com.attunedlabs.eventframework.dispatcher.transformer.GenericLeapEventJsonTransformer"/>
					</EventTransformation>
				</EventDispatcher>
			</EventDispatchers>
		</Event>
		<Event description="print service" id="PRINT_SERVICE" isEnabled="false" type="internal">
			<EventParams>
				<EventParam dataType="string" name="eventid" validationRegEx=""/>
				<EventParam dataType="string" name="tenantid" validationRegEx=""/>
			</EventParams>
			<CamelEventProducer>
				<CamelProducerConfig component="com.attunedlabs.wms20.services.printlabel.PrintLabel" feature="labelservice" raiseOn="success" serviceName="baseContext"/>
				<CamelEventBuilder type="OGNL">
					<OGNLMapping>
						<Source from="CamelExchange">
							<EventMapping destination="eventParam['servicetype']" source="In.headers['servicetype']"/>
							<EventMapping destination="eventParam['tenant']" source="In.headers['tenantid']"/>
						</Source>
					</OGNLMapping>
				</CamelEventBuilder>
			</CamelEventProducer>
			<EventDispatchers>
				<EventDispatcher>
					<dis:DispatchChanelId>EVT_FILE_STORE</dis:DispatchChanelId>
					<EventTransformation Type="CUSTOM">
						<CustomTransformer fqcn="com.attunedlabs.eventframework.dispatcher.transformer.GenericLeapEventJsonTransformer"/>
					</EventTransformation>
				</EventDispatcher>
			</EventDispatchers>
		</Event>
	</Events>
</EventFramework>
