=== satishkumar9142/Task/XML/src/main/resources/Entity.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="LeapDataServices">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Entity">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="EntityFields">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="EntityField">
                      <xs:complexType>
                        <xs:attribute name="name" type="xs:string" use="required" />
                        <xs:attribute name="type" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="EntityCollection">
                <xs:complexType>
                  <xs:attribute name="collectionName" type="xs:string" use="required" />
                  <xs:attribute name="collectionType" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
              <xs:element name="EntityAccessConfig">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="EntityTable">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="EntityColumns">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element maxOccurs="unbounded" name="EntityColumn">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element maxOccurs="unbounded" name="Attribute">
                                        <xs:complexType>
                                          <xs:attribute name="name" type="xs:string" use="required" />
                                          <xs:attribute name="value" type="xs:string" use="required" />
                                          <xs:attribute name="attributeDatatype" type="xs:string" use="optional" />
                                          <xs:attribute name="type" type="xs:string" use="optional" />
                                          <xs:attribute name="size" type="xs:unsignedByte" use="optional" />
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="entityFieldNameRef" type="xs:string" use="required" />
                                    <xs:attribute name="hasAutoIncrement" type="xs:boolean" use="optional" />
                                    <xs:attribute name="name" type="xs:string" use="required" />
                                    <xs:attribute name="sequence" type="xs:unsignedByte" use="optional" />
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="EntityIndexs">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="EntityIndex">
                                  <xs:complexType>
                                    <xs:attribute name="entityColumnRef" type="xs:string" use="required" />
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="autoCreate" type="xs:boolean" use="required" />
                        <xs:attribute name="tablename" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                    <xs:element maxOccurs="unbounded" name="EntityAccess">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element minOccurs="0" name="EntityUpdateKeysMapping">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element maxOccurs="unbounded" name="EntityKey">
                                  <xs:complexType>
                                    <xs:attribute name="name" type="xs:string" use="required" />
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element minOccurs="0" name="EntityInsertKeysMapping">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element maxOccurs="unbounded" name="EntityKey">
                                  <xs:complexType>
                                    <xs:attribute name="name" type="xs:string" use="required" />
                                    <xs:attribute name="required" type="xs:string" use="required" />
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element minOccurs="0" name="EntityReadKeysMapping">
                            <xs:complexType>
                              <xs:sequence minOccurs="0">
                                <xs:element maxOccurs="unbounded" name="EntityKey">
                                  <xs:complexType>
                                    <xs:attribute name="name" type="xs:string" use="required" />
                                    <xs:attribute name="sequence" type="xs:unsignedByte" use="required" />
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element minOccurs="0" name="EntityFilterKeysMapping">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element maxOccurs="unbounded" name="EntityKey">
                                  <xs:complexType>
                                    <xs:attribute name="mappedTo" type="xs:string" use="optional" />
                                    <xs:attribute name="name" type="xs:string" use="required" />
                                    <xs:attribute name="required" type="xs:string" use="required" />
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element minOccurs="0" name="LDCResponseConfigs">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="ApplyLDCConfig">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="LDCSchema">
                                        <xs:complexType>
                                          <xs:attribute name="required" type="xs:boolean" use="required" />
                                          <xs:attribute name="schemaFileName" type="xs:string" use="required" />
                                        </xs:complexType>
                                      </xs:element>
                                      <xs:element name="LDCProjection">
                                        <xs:complexType>
                                          <xs:attribute name="projectionFileName" type="xs:string" use="required" />
                                          <xs:attribute name="projectionSource" type="xs:string" use="required" />
                                          <xs:attribute name="required" type="xs:boolean" use="required" />
                                        </xs:complexType>
                                      </xs:element>
                                      <xs:element name="LDCTaxonomy">
                                        <xs:complexType>
                                          <xs:attribute name="required" type="xs:boolean" use="required" />
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="applyAt" type="xs:string" use="required" />
                                    <xs:attribute name="sequence" type="xs:unsignedByte" use="required" />
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="accessMethod" type="xs:string" use="required" />
                        <xs:attribute name="accessType" type="xs:string" use="required" />
                        <xs:attribute name="authorizedResource" type="xs:string" use="required" />
                        <xs:attribute name="isCollection" type="xs:boolean" use="optional" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="type" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="isEnable" type="xs:boolean" use="required" />
            <xs:attribute name="name" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="version" type="xs:decimal" use="required" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== satishkumar9142/Task/XML/target/classes/Entity.xml
<?xml version="1.0" encoding="UTF-8"?>
<LeapDataServices version="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="entity.xsd">
	<Entity isEnable="true" name="WMS_Employee">
		<!-- one or more entity can be defined -->
		<EntityFields>
			<EntityField name="Emp_Id" type="long"/>
			<EntityField name="Emp_Name" type="string"/>
			<EntityField name="Emp_Salary" type="double"/>
			<EntityField name="Emp_Email" type="string"/>
		</EntityFields>
		<EntityCollection collectionName="WMS_Employees" collectionType="list"/>
		<EntityAccessConfig type="SQL">
			<EntityTable autoCreate="true" tablename="employee1">
				<EntityColumns>
					<EntityColumn entityFieldNameRef="Emp_Id" hasAutoIncrement="true" name="id" sequence="2">
						<Attribute name="dataType" value="long"/>
						<Attribute name="isPrimaryKey" value="true"/>
						<Attribute attributeDatatype="Number" name="autoIncrement" type="MANUAL" value="SNOWFLAKE"/>
					</EntityColumn>
					<EntityColumn entityFieldNameRef="Emp_Name" name="empName">
						<Attribute attributeDatatype="String" name="DataType" size="30" value="varchar"/>
					</EntityColumn>
					<EntityColumn entityFieldNameRef="Emp_Salary" name="salary">
						<Attribute name="DataType" value="Double"/>
					</EntityColumn>
					<EntityColumn entityFieldNameRef="Emp_Email" name="email" sequence="1">
						<Attribute name="DataType" size="30" value="varchar"/>
						<Attribute name="isNotNull" value="true"/>
					</EntityColumn>
				</EntityColumns>
				<EntityIndexs>
					<EntityIndex entityColumnRef="id"/>
				</EntityIndexs>
			</EntityTable>
			<EntityAccess accessMethod="GET" accessType="read" authorizedResource="getWmsEmployeeById">
				<EntityReadKeysMapping>
					<EntityKey name="Emp_Id" sequence="1"/>
					<EntityKey name="Emp_Name" sequence="2"/>
					<EntityKey name="Emp_Salary" sequence="3"/>
					<EntityKey name="Emp_Email" sequence="4"/>
				</EntityReadKeysMapping>
				<EntityFilterKeysMapping>
					<EntityKey mappedTo="Employee_Id" name="Emp_Id" required="mandatory"/>
				</EntityFilterKeysMapping>
				<LDCResponseConfigs>
					<ApplyLDCConfig applyAt="impl" sequence="1">
						<LDCSchema required="false" schemaFileName="schemaFileName"/>
						<LDCProjection projectionFileName="EntityTest_Test_test_QW_Swagger.json" projectionSource="swagger" required="false"/>
						<LDCTaxonomy required="false"/>
					</ApplyLDCConfig>
				</LDCResponseConfigs>
			</EntityAccess>
			<EntityAccess accessMethod="GET" accessType="read" authorizedResource="getAllWmsEmployees" isCollection="true">
				<EntityReadKeysMapping>
				</EntityReadKeysMapping>
				<LDCResponseConfigs>
					<ApplyLDCConfig applyAt="impl" sequence="1">
						<LDCSchema required="false" schemaFileName="schemaFileName"/>
						<LDCProjection projectionFileName="EntityTest_Test_test_QW_Swagger.json" projectionSource="swagger" required="false"/>
						<LDCTaxonomy required="true"/>
					</ApplyLDCConfig>
				</LDCResponseConfigs>
			</EntityAccess>
			<EntityAccess accessMethod="POST" accessType="Create" authorizedResource="insertWmsEmployee">
				<EntityInsertKeysMapping>
					<EntityKey name="Emp_Name" required="mandatory"/>
					<EntityKey name="Emp_Salary" required="optional"/>
					<EntityKey name="Emp_Email" required="optional"/>
				</EntityInsertKeysMapping>
			</EntityAccess>
			<EntityAccess accessMethod="POST" accessType="Update" authorizedResource="updateWmsEmployeeByIdAndName">
				<EntityUpdateKeysMapping>
					<EntityKey name="Emp_Salary"/>
					<EntityKey name="Emp_Email"/>
				</EntityUpdateKeysMapping>
				<EntityFilterKeysMapping>
					<EntityKey name="Emp_Id" required="mandatory"/>
					<EntityKey name="Emp_Name" required="optional"/>
				</EntityFilterKeysMapping>
			</EntityAccess>
			<EntityAccess accessMethod="GET" accessType="Delete" authorizedResource="deleteWmsEmployeeById">
				<EntityFilterKeysMapping>
					<EntityKey name="Emp_Id" required="mandatory"/>
				</EntityFilterKeysMapping>
			</EntityAccess>
		</EntityAccessConfig>
	</Entity>
</LeapDataServices>
